version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - stylecheck
    - unconvert
    - unparam
    - gosec
    - gocritic

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    check-shadowing: true
  
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: var-naming
        severity: warning
        disabled: false
  
  gosec:
    excludes:
      - G304  # Allow dynamic file paths for legitimate use cases
  
  gocritic:
    enabled-checks:
      - appendCombine
      - boolExprSimplify
      - dupBranchBody
      - dupImport
      - emptyFallthrough
      - hexLiteral
      - ifElseChain
      - nilValReturn
      - regexpMust
      - singleCaseSwitch
      - sloppyLen
      - typeSwitchVar
      - underef
      - unlambda
      - unslice

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
  
  max-same-issues: 0
  max-issues-per-linter: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

